# Generated by Django 3.1.2 on 2020-11-14 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=500)),
                ('product_category', models.CharField(max_length=200)),
                ('product_description', models.CharField(max_length=5000)),
                ('product_price', models.IntegerField()),
            ],
        ),
    ]
