# Generated by Django 3.1.2 on 2020-11-14 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceWebsite', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
