# Generated by Django 3.1.2 on 2020-11-21 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceWebsite', '0003_contactus'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactUs',
            new_name='ContactUsResponse',
        ),
    ]
