# Generated by Django 3.1.2 on 2020-11-23 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceWebsite', '0005_cartitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='cutomer_id',
            new_name='customer_id',
        ),
    ]
