# Generated by Django 3.1.2 on 2020-11-23 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceWebsite', '0006_auto_20201123_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='product_add_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
