# Generated by Django 3.1.2 on 2020-12-02 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('blog_id', models.AutoField(primary_key=True, serialize=False)),
                ('blog_heading', models.CharField(max_length=200)),
                ('blog_subheading', models.CharField(max_length=100)),
                ('blog_content', models.CharField(max_length=2000)),
                ('blog_addedBy', models.CharField(max_length=50)),
                ('blog_pubDate', models.DateField(auto_now=True)),
                ('blog_image', models.ImageField(default='', upload_to='media')),
            ],
        ),
    ]
